# Event parameters ------------------------------------------------------------
edition: 2023
title: Microservices 2023
baseurl: /2023
header:
  city: "Pisa"
  dates: "October 10-12, 2023"
email: microservices2023@microservices.community # contact email
description: "Academia meets Industry"
timezone: Europe/Rome
twitter_feed: c_microservices
# legal_notice_url: /legal-notice
community_badge:
  asset: "1-black.png"
  token: "microservices2023"

# Site navigation -------------------------------------------------------------
navigation_header:
  Home: /
  Program:  /program/
  Attending: /attending/
  Keynotes: /keynotes/
  Committees: /committees/
  Registration: /registration/
  Contact: /contact/
  Code of Conduct: https://www.microservices.community/events/coc/

# Exclude from build -----------------------------------------------------------

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Makefile
  - alembic-jekyll-theme.gemspec

#------------------------------------------------------------------------------
logo: "/assets/images/microservices.svg"
url: "https://conf-micro.services/"
avatarurl: "/assets/images/favicon.ico"

encoding: utf-8

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji

sass:
  style: compressed # Style compression
permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      feature_image: "pisa_square.jpg"
      # image_source: "Microservice Community"
